from __future__ import annotations

import re
from pathlib import Path


def _matlab_identifier(value: str) -> str:
    """Return a conservative MATLAB function/script identifier."""

    cleaned = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_") or "export"
    if not cleaned[0].isalpha():
        cleaned = f"f_{cleaned}"
    return cleaned[:48]


def _matlab_string(value: str) -> str:
    """Escape a value for a single-quoted MATLAB character vector."""

    return value.replace("'", "''")


def write_matlab_table_loader(mat_path: str | Path) -> Path:
    """Write a companion MATLAB script that exposes the MAT data as tables.

    SciPy writes standard MAT arrays/structs, not MATLAB class objects such as
    ``table`` or ``timetable``.  The generated script converts the numeric
    matrices already contained in the export into native MATLAB containers with
    named variables and keeps the complete loaded MAT payload in ``data``.
    """

    path = Path(mat_path).expanduser().resolve()
    script_name = f"load_{_matlab_identifier(path.stem)}.m"
    script_path = path.with_name(script_name)
    mat_name = _matlab_string(path.name)

    source = f"""% Auto-generated by GPS-Routenplaner.
% Run this script from MATLAB to load the complete export and create native
% tables/timetables in the current workspace.
%
% Created variables:
%   data                 complete raw MAT payload
%   distanceTable        route data indexed by distance
%   driveTable           complete time-aligned table including time_s
%   driveTimetable       time-aligned native timetable
%   powerTimetable       power/energy subset of driveTimetable
%   trafficLightTable    detected/simulated traffic-light stops
%   routeCoordinateTable original route coordinates

loaderFile = mfilename('fullpath');
loaderDir = fileparts(loaderFile);
data = load(fullfile(loaderDir, '{mat_name}'));

%% Distance-aligned route table
distanceNames = string(data.distance_columns(:))';
distanceNames = matlab.lang.makeUniqueStrings(matlab.lang.makeValidName(distanceNames));
distanceTable = array2table(data.distance_table, 'VariableNames', cellstr(distanceNames));

%% Time-aligned table and timetable
timeNames = string(data.time_columns(:))';
timeNames = matlab.lang.makeUniqueStrings(matlab.lang.makeValidName(timeNames));
driveTable = array2table(data.time_table, 'VariableNames', cellstr(timeNames));

if ~ismember('time_s', driveTable.Properties.VariableNames)
    error('GPS-Routenplaner:MissingTime', 'time_s fehlt im MAT-Export.');
end
rowTime = seconds(driveTable.time_s);
driveTimetable = table2timetable(removevars(driveTable, 'time_s'), 'RowTimes', rowTime);
driveTimetable.Properties.DimensionNames{{1}} = 'Time';

%% Power/energy view with the same timetable row times
powerNames = {{ ...
    'total_kw', 'acceleration_kw', 'grade_kw', 'rolling_kw', 'air_kw', ...
    'trailer_kw', 'traction_power_kw', 'recuperation_power_kw', ...
    'cumulative_traction_energy_kwh', 'cumulative_recuperation_energy_kwh', ...
    'cumulative_net_energy_kwh' ...
}};
powerNames = powerNames(ismember(powerNames, driveTimetable.Properties.VariableNames));
powerTimetable = driveTimetable(:, powerNames);

%% Traffic-light table
trafficLightTable = table();
if isfield(data, 'events') && isfield(data.events, 'traffic_lights')
    trafficData = data.events.traffic_lights;
    if ~isempty(trafficData)
        trafficNames = string(data.events.traffic_lights_columns(:))';
        trafficNames = matlab.lang.makeUniqueStrings(matlab.lang.makeValidName(trafficNames));
        trafficLightTable = array2table(trafficData, 'VariableNames', cellstr(trafficNames));
    end
end

%% Original route-coordinate table
routeCoordinateTable = table();
if isfield(data, 'route_coordinates') && ~isempty(data.route_coordinates)
    coordinateNames = string(data.route_coordinate_columns(:))';
    coordinateNames = matlab.lang.makeUniqueStrings(matlab.lang.makeValidName(coordinateNames));
    routeCoordinateTable = array2table(data.route_coordinates, 'VariableNames', cellstr(coordinateNames));
end

clear loaderFile loaderDir distanceNames timeNames rowTime powerNames trafficData trafficNames coordinateNames;

disp('GPS-Routenplaner export geladen:');
disp(['  distanceTable:     ' num2str(height(distanceTable)) ' Zeilen']);
disp(['  driveTimetable:    ' num2str(height(driveTimetable)) ' Zeilen']);
disp(['  powerTimetable:    ' num2str(height(powerTimetable)) ' Zeilen']);
disp(['  trafficLightTable: ' num2str(height(trafficLightTable)) ' Zeilen']);
"""

    script_path.write_text(source, encoding="utf-8", newline="\n")
    return script_path
