from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

import numpy as np
from scipy.io import loadmat, savemat

try:
    from .mat_export import export_matlab_simulation as _base_export
except ImportError:
    from mat_export import export_matlab_simulation as _base_export


_EXCLUDED_PREFIXES = (
    "route_",
    "traffic_light_",
    "post_curve_",
    "overtaking_",
    "event_",
    "segment_",
    "osm_signal_",
    "leg_",
    "param_",
    "summary_",
    "comparison_",
    "load_",
)


def _flat(value: Any) -> np.ndarray:
    try:
        return np.asarray(value, dtype=np.float64).reshape(-1)
    except (TypeError, ValueError):
        return np.empty(0, dtype=np.float64)


def _column(value: Any, length: int) -> np.ndarray:
    values = _flat(value)
    if values.size != length:
        raise ValueError(
            f"Synchronisiertes Signal hat Länge {values.size}, erwartet wird {length}."
        )
    return values.reshape(-1, 1)


def _sorted_unique_axis(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    finite = np.isfinite(x) & ~np.isnan(y)
    x = x[finite]
    y = y[finite]
    if x.size == 0:
        return x, y
    order = np.argsort(x, kind="stable")
    x = x[order]
    y = y[order]
    x, indexes = np.unique(x, return_index=True)
    return x, y[indexes]


def _interp(route_distance: np.ndarray, values: np.ndarray, query: np.ndarray) -> np.ndarray:
    x, y = _sorted_unique_axis(route_distance, values)
    if x.size == 0:
        return np.full(query.size, np.nan, dtype=np.float64)
    if x.size == 1:
        return np.full(query.size, y[0], dtype=np.float64)
    return np.interp(query, x, y)


def _nearest(route_distance: np.ndarray, values: np.ndarray, query: np.ndarray) -> np.ndarray:
    x, y = _sorted_unique_axis(route_distance, values)
    if x.size == 0:
        return np.full(query.size, np.nan, dtype=np.float64)
    if x.size == 1:
        return np.full(query.size, y[0], dtype=np.float64)
    positions = np.searchsorted(x, query, side="left")
    right = np.clip(positions, 0, x.size - 1)
    left = np.clip(positions - 1, 0, x.size - 1)
    use_right = np.abs(query - x[right]) < np.abs(query - x[left])
    return y[np.where(use_right, right, left)]


def _route_field_uses_interpolation(name: str) -> bool:
    continuous_tokens = (
        "lat_deg",
        "lon_deg",
        "elevation",
        "grade",
        "planned",
        "actual",
        "noise",
        "boost",
        "target",
    )
    return any(token in name for token in continuous_tokens)


def _synchronized_signals(workspace: Mapping[str, Any]) -> dict[str, np.ndarray]:
    time_s = _flat(workspace.get("time_s", []))
    distance_m = _flat(workspace.get("distance_m", []))
    if time_s.size == 0:
        raise ValueError("MAT-Export enthält keinen Zeitvektor time_s.")
    if distance_m.size != time_s.size:
        raise ValueError(
            "distance_m und time_s müssen für den synchronisierten Simulationseingang "
            "dieselbe Länge besitzen."
        )

    n = time_s.size
    signals: dict[str, np.ndarray] = {
        "sample_index": np.arange(n, dtype=np.float64).reshape(-1, 1),
    }

    # All already time-synchronous top-level signals are copied first. This
    # includes speed, acceleration, limits, radius, elevation and power arrays
    # generated by mat_export.py.
    for name, value in workspace.items():
        if name.startswith("__") or name == "sim":
            continue
        if name.startswith(_EXCLUDED_PREFIXES):
            continue
        array = _flat(value)
        if array.size == n:
            signals[name] = array.reshape(-1, 1)

    # Optional spatial route signals can have another sampling grid. Convert
    # every numeric route_* vector that matches route_distance_m to the master
    # time grid. Existing synchronized names always win.
    route_distance = _flat(workspace.get("route_distance_m", []))
    if route_distance.size >= 1:
        for name, value in workspace.items():
            if not name.startswith("route_") or name == "route_distance_m":
                continue
            source = _flat(value)
            if source.size != route_distance.size:
                continue
            target_name = name[len("route_") :]
            if target_name in signals:
                continue
            if _route_field_uses_interpolation(target_name):
                synchronized = _interp(route_distance, source, distance_m)
            else:
                synchronized = _nearest(route_distance, source, distance_m)
            signals[target_name] = synchronized.reshape(-1, 1)

    # Contract: every simulation input is an N x 1 double vector.
    for name, value in list(signals.items()):
        signals[name] = _column(value, n)
    return signals


def export_matlab_simulation(
    result: Mapping[str, Any],
    output_path: str | Path,
    *,
    route: Mapping[str, Any] | None = None,
    parameters: Mapping[str, Any] | None = None,
    power_data: Mapping[str, Any] | None = None,
    elevation_m: np.ndarray | None = None,
    source_route: str | Path | None = None,
    source_dem: str | Path | None = None,
    comparison: Mapping[str, Any] | None = None,
) -> Path:
    """Export the normal MAT workspace plus one strict synchronous input block.

    ``sim_input`` and every top-level ``input_*`` variable use exactly the same
    N x 1 time grid as ``time_s``. Raw route geometry, event lists, summaries
    and scalar metadata remain available separately and deliberately keep their
    natural lengths.
    """

    path = _base_export(
        result,
        output_path,
        route=route,
        parameters=parameters,
        power_data=power_data,
        elevation_m=elevation_m,
        source_route=source_route,
        source_dem=source_dem,
        comparison=comparison,
    )

    loaded = loadmat(path)
    workspace: dict[str, Any] = {
        key: value for key, value in loaded.items() if not key.startswith("__")
    }
    signals = _synchronized_signals(workspace)

    for name, value in signals.items():
        workspace[f"input_{name}"] = np.asarray(value, dtype=np.float64)
    workspace["sim_input"] = {
        name: np.asarray(value, dtype=np.float64) for name, value in signals.items()
    }

    savemat(
        path,
        workspace,
        appendmat=False,
        do_compression=True,
        long_field_names=True,
    )
    return path


__all__ = ["export_matlab_simulation"]
